# Generated by Django 2.2.6 on 2024-05-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0004_add_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeplan',
            name='order',
            field=models.IntegerField(),
        ),
    ]
